/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
/**
 *
 * @author gleider
 */
public class RegistrarEscultura extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarEscultura
     */
    public RegistrarEscultura() {
        initComponents();
    }
    
    public void apagar(){
        jTextFieldAltura.setText("");
        jTextFieldAutor.setText("");
        jTextFieldComprimento.setText("");
        jTextFieldEspessura.setText("");
        jTextFieldForma.setText("");
        jTextFieldLargura.setText("");
        jTextFieldMaiorCirc.setText("");
        jTextFieldMaterialUtilizado.setText("");
        jTextFieldMenorCirc.setText("");
        jTextFieldPeso.setText("");
        jTextFieldProfundidade.setText("");
        jTextFieldTecnica.setText("");
    }
    
    public void setFields(String altura, ArrayList<String> autores, String comprimento, String espessura, String forma, String largura, String maiorCirc
            , ArrayList<String> materiais, String menorCirc, String peso, String profundidade, String tecnica)
    {
        jTextFieldAltura.setText(altura);
        for(String a : materiais){
            jComboBoxAutores.addItem(a);

        }
        
        jTextFieldComprimento.setText(comprimento);
        jTextFieldEspessura.setText(espessura);
        jTextFieldForma.setText(forma);
        jTextFieldLargura.setText(largura);
        jTextFieldMenorCirc.setText(menorCirc);
        jTextFieldMaiorCirc.setText(maiorCirc);
        for(String a : materiais){
            jComboBoxMateriais.addItem(a);
           
        }
        
        jTextFieldPeso.setText(peso);
        jTextFieldProfundidade.setText(profundidade);
        jTextFieldTecnica.setText(tecnica);
    }

    public ArrayList<String> getjComboBoxAutores() {
        ArrayList<String> autores = new ArrayList<>();
        for(int i=1;i<jComboBoxAutores.getItemCount();i++){
            autores.add(jComboBoxAutores.getItemAt(i));
        }
        return autores;
    }

    public ArrayList<String> getjComboBoxMateriais() {
        ArrayList<String> materiais = new ArrayList<>();
        for(int i=1;i<jComboBoxMateriais.getItemCount();i++){
            materiais.add(jComboBoxMateriais.getItemAt(i));
        }
        return materiais;
    }

    public double getjTextFieldAltura() {
        String altura = jTextFieldAltura.getText();
        altura = altura.replace(",", ".");
        return Double.parseDouble(altura);
    }

    public double getjTextFieldComprimento() {
        String comprimento = jTextFieldComprimento.getText();
        comprimento = comprimento.replace(",", ".");
        return Double.parseDouble(comprimento);
    }

    public double getjTextFieldEspessura() {
        String espessura = jTextFieldEspessura.getText();
        espessura = espessura.replace(",", ".");
        return Double.parseDouble(espessura);
    }

    public String getjTextFieldForma() {
        return jTextFieldForma.getText();
    }

    public double getjTextFieldLargura() {
        String largura = jTextFieldLargura.getText();
        largura = largura.replace(",", ".");
        return Double.parseDouble(largura);
    }

    public double getjTextFieldMaiorCirc() {
        String maiorCirc = jTextFieldMaiorCirc.getText();
        maiorCirc = maiorCirc.replace(",", ".");
        return Double.parseDouble(maiorCirc);
    }

    public double getjTextFieldMenorCirc() {
        String menorCirc = jTextFieldMenorCirc.getText();
        menorCirc = menorCirc.replace(",", ".");
        return Double.parseDouble(menorCirc);
    }

    public double getjTextFieldPeso() {
        String peso = jTextFieldPeso.getText();
        peso = peso.replace(",", ".");
        return Double.parseDouble(peso);
    }

    public double getjTextFieldProfundidade() {
        String profundidade = jTextFieldProfundidade.getText();
        profundidade = profundidade.replace(",", ".");
        return Double.parseDouble(profundidade);
    }

    public String getjTextFieldTecnica() {
        return jTextFieldTecnica.getText();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldTecnica = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldForma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMaterialUtilizado = new javax.swing.JTextField();
        jButtonAdicionarMaterial = new javax.swing.JButton();
        jComboBoxMateriais = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jButtonAdicionarAutor = new javax.swing.JButton();
        jComboBoxAutores = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldComprimento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLargura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldEspessura = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldProfundidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldMaiorCirc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMenorCirc = new javax.swing.JTextField();
        jButtonRemoverMaterial = new javax.swing.JButton();
        jButtonRemoverAutor = new javax.swing.JButton();

        jLabel1.setText("Técnica");

        jLabel2.setText("Forma");

        jLabel3.setText("Material utilizado");

        jButtonAdicionarMaterial.setText("Adicionar");
        jButtonAdicionarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarMaterialActionPerformed(evt);
            }
        });

        jComboBoxMateriais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materiais" }));

        jLabel4.setText("Autor");

        jButtonAdicionarAutor.setText("Adicionar");
        jButtonAdicionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAutorActionPerformed(evt);
            }
        });

        jComboBoxAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autores" }));

        jLabel5.setText("Peso(kg)");

        jLabel6.setText("Comprimento");

        jLabel7.setText("Largura(cm)");

        jLabel8.setText("Altura(cm)");

        jLabel9.setText("Espessura(cm)");

        jLabel10.setText("Profundidade");

        jLabel11.setText("Maior circunferência(cm)");

        jLabel12.setText("Menor circunferência(cm)");

        jButtonRemoverMaterial.setText("Remover");
        jButtonRemoverMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverMaterialActionPerformed(evt);
            }
        });

        jButtonRemoverAutor.setText("Remover");
        jButtonRemoverAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTecnica))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxMateriais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMaterialUtilizado, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAdicionarMaterial)
                                    .addComponent(jButtonRemoverMaterial))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldForma, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxAutores, 0, 325, Short.MAX_VALUE)
                            .addComponent(jTextFieldAutor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRemoverAutor)
                            .addComponent(jButtonAdicionarAutor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldMaiorCirc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldMenorCirc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProfundidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMaterialUtilizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoverMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoverAutor))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextFieldComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextFieldProfundidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldMaiorCirc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldMenorCirc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarMaterialActionPerformed
        if(!jTextFieldMaterialUtilizado.getText().isEmpty()){
            jComboBoxMateriais.addItem(jTextFieldMaterialUtilizado.getText());
            jTextFieldMaterialUtilizado.setText("");
        }
    }//GEN-LAST:event_jButtonAdicionarMaterialActionPerformed

    private void jButtonRemoverMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverMaterialActionPerformed
        if(!jComboBoxMateriais.getSelectedItem().equals("Materiais"))
            jComboBoxMateriais.removeItem(jComboBoxMateriais.getSelectedItem());
    }//GEN-LAST:event_jButtonRemoverMaterialActionPerformed

    private void jButtonAdicionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAutorActionPerformed
        if(!jTextFieldAutor.getText().isEmpty()){
            jComboBoxAutores.addItem(jTextFieldAutor.getText());
            jTextFieldAutor.setText("");
        }
    }//GEN-LAST:event_jButtonAdicionarAutorActionPerformed

    private void jButtonRemoverAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverAutorActionPerformed
        if(!jComboBoxAutores.getSelectedItem().equals("Autores")){
            jComboBoxAutores.removeItem(jComboBoxAutores.getSelectedItem());
        }
    }//GEN-LAST:event_jButtonRemoverAutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarAutor;
    private javax.swing.JButton jButtonAdicionarMaterial;
    private javax.swing.JButton jButtonRemoverAutor;
    private javax.swing.JButton jButtonRemoverMaterial;
    private javax.swing.JComboBox<String> jComboBoxAutores;
    private javax.swing.JComboBox<String> jComboBoxMateriais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldComprimento;
    private javax.swing.JTextField jTextFieldEspessura;
    private javax.swing.JTextField jTextFieldForma;
    private javax.swing.JTextField jTextFieldLargura;
    private javax.swing.JTextField jTextFieldMaiorCirc;
    private javax.swing.JTextField jTextFieldMaterialUtilizado;
    private javax.swing.JTextField jTextFieldMenorCirc;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldProfundidade;
    private javax.swing.JTextField jTextFieldTecnica;
    // End of variables declaration//GEN-END:variables
}
