/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import controle.Principal;



/**
 *
 * @author Gleider
 */
public class VisaoPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    private Principal control;
    public VisaoPrincipal() {
        initComponents();
        control = Principal.getInstance();
        jLabelNomeUsuario.setText(control.getNomeUsuarioAutenticado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBusca = new javax.swing.JTextField();
        jButtonBuscaObra = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemRegObra = new javax.swing.JMenuItem();
        jMenuItemRegMuseu = new javax.swing.JMenuItem();
        jMenuItemRegColecao = new javax.swing.JMenuItem();
        jMenuItemRegUsuario = new javax.swing.JMenuItem();
        jMenuConUsuario = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItemConObra = new javax.swing.JMenuItem();
        jMenuItemConMuseu = new javax.swing.JMenuItem();
        jMenuItemConColecao = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Museo");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Bem-vindo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Buscar Obras");
        jLabel2.setEnabled(false);

        jTextFieldBusca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaActionPerformed(evt);
            }
        });

        jButtonBuscaObra.setText("Buscar");
        jButtonBuscaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaObraActionPerformed(evt);
            }
        });

        jButtonLogin.setText("Autenticar");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Encerrar sessão");
        jButtonLogout.setEnabled(false);
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButtonBuscaObra, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonLogin)
                    .addComponent(jLabelNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogout)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscaObra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu7.setText("Registrar");

        jMenuItemRegObra.setText("Obra");
        jMenuItemRegObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegObraActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemRegObra);

        jMenuItemRegMuseu.setText("Museu");
        jMenuItemRegMuseu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegMuseuActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemRegMuseu);

        jMenuItemRegColecao.setText("Coleção");
        jMenuItemRegColecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegColecaoActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemRegColecao);

        jMenuItemRegUsuario.setText("Usuário");
        jMenuItemRegUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegUsuarioActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemRegUsuario);

        jMenuBar1.add(jMenu7);

        jMenuConUsuario.setText("Consultar");

        jMenuItem11.setText("Usuário");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenuConUsuario.add(jMenuItem11);

        jMenuItemConObra.setText("Obra");
        jMenuConUsuario.add(jMenuItemConObra);

        jMenuItemConMuseu.setText("Museu");
        jMenuConUsuario.add(jMenuItemConMuseu);

        jMenuItemConColecao.setText("Coleção");
        jMenuConUsuario.add(jMenuItemConColecao);

        jMenuBar1.add(jMenuConUsuario);

        jMenu6.setText("Sobre");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
       SelecaoUsuario su = new SelecaoUsuario();
       su.setVisible(true);
    }//GEN-LAST:event_jButtonLoginActionPerformed
    
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        
        if(control.checaPermissaoTecnico())
        {
                RegistrarUsuario ru = new RegistrarUsuario();
                ru.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Acesso restrito","Voce nao tem as permissoes necessarias para acessar esta opcao.",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButtonBuscaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaObraActionPerformed
        if(jTextFieldBusca.getText().equals(""))
        {
            ResultadoObra rb = new ResultadoObra();
            rb.setVisible(true);
        }
        else
        {
            ResultadoObra rb = new ResultadoObra();
            rb.setVisible(true);
        }
    }//GEN-LAST:event_jButtonBuscaObraActionPerformed

    public static void uiAutentica(String nome)
    {
        jLabelNomeUsuario.setText(nome);
        jButtonLogout.setEnabled(true);
    }
    private void jMenuItemRegObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegObraActionPerformed
        if(control.checaPermissaoTecnico()) //RESTRINGIR SOMENTE A TECNICOS NO FUTURO!!
        {
            RegistrarObra ro = new RegistrarObra();
            ro.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Acesso restrito","Voce nao tem as permissoes necessarias para acessar esta opcao.",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemRegObraActionPerformed

    private void jMenuItemRegUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegUsuarioActionPerformed
        if(control.checaPermissaoTecnico())
        {
            RegistrarUsuario ru = new RegistrarUsuario();
            ru.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Area restrita","Usuário sem permissão de cadastro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemRegUsuarioActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja finalizar sua sessão?", "", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
          control.autenticaVisitante();
          jButtonLogout.setEnabled(false);
          jLabelNomeUsuario.setText("Visitante");
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jMenuItemRegMuseuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegMuseuActionPerformed
        if(control.checaPermissaoCoordenador())
        {
            RegistrarMuseu rm = new RegistrarMuseu();
            rm.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Usuário não autorizado", "Área Restrita", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemRegMuseuActionPerformed

    private void jMenuItemRegColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegColecaoActionPerformed
        if(control.checaPermissaoTecnico())
        {
            RegistrarColecao rc = new RegistrarColecao();
            rc.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Usuário não autorizado", "Área Restrita", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemRegColecaoActionPerformed

    private void jTextFieldBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscaActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        if(control.checaPermissaoTecnico())
        {
            ListarUsuarios lu = new ListarUsuarios();
            lu.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Usuário não autorizado", "Área Restrita", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscaObra;
    private javax.swing.JButton jButtonLogin;
    private static javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConUsuario;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItemConColecao;
    private javax.swing.JMenuItem jMenuItemConMuseu;
    private javax.swing.JMenuItem jMenuItemConObra;
    private javax.swing.JMenuItem jMenuItemRegColecao;
    private javax.swing.JMenuItem jMenuItemRegMuseu;
    private javax.swing.JMenuItem jMenuItemRegObra;
    private javax.swing.JMenuItem jMenuItemRegUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBusca;
    // End of variables declaration//GEN-END:variables
}
